### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by thomas18F**

### CODE REVIEW

**Comment by FallenDeity** [comment]
Are you planning to actively maintain this package, I am quite interested in this and would love to contribute as I am planning on working on something similar but with data compatible with pokeapi where u can take data from here and plug in/generate crucial values for pokemon (eg: ivs, evs) imo it would make the process of making games related to pokemon much easier.

**Comment by thomas18F** [comment]
Hello, yes, I am gonna sort of maintain it actively. For now, I am trying to rewrite the existing code as I found many errors or unnecesary code. But yes, I planed to add functionalities and for example as you mention it, I would like to modify the way datas are stocked because csv seems ugly.
Feel free to make your own suggestions or corrections ;)

**Comment by FallenDeity** [comment]
Right i am gonna look into the package code over this weekend and figure out how it works perhaps a tasklist of goals that can be met would be a good addition as a record and also for better collaboration I believe it would help with making prs for anyone looking to contribute. The project as in of itself seems pretty amazing since the only viable alternative is the showdown simulator package wrappers which use browser agents and a showdown server and are pretty heavy to use

**Comment by FallenDeity** [comment]
Also for the current data storage I would recommend probably making some online storage can be github or some other custom endpoint, if you are using some custom datasets or formats export them and query them when needed from some api since packaging them with the library seems kinda heavy and unecessary or perhaps query data from the api during initialisation of battles or teams of sort well there could be better ways I'll probably get back to you once I am up to date on the package 🙂

**Comment by thomas18F** [comment]
For now, main goals are just to correct the package and add what is missing, but after yes, it may be interesting to add a tasklist.

I don't understand why you would switch to an online API, it would complexify the code, increase the dependancies, restrict the offline usage and reduce the customization possibilities. Also I am not sure about the problem of the data size.

**Pull request merged**
